### ISSUE TITLE
footer overlap

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website-v2#41]
Hi all, the footer gets overlapped by the sidebar on some pages, eg:
<img width="1238" alt="Screen Shot 2020-03-02 at 3 53 26 PM" src="https://user-images.githubusercontent.com/17657625/75721466-06fc2f00-5c9e-11ea-8525-4f2edb44d7d3.png">

**Comment by monikappv** [comment]
hi @lwinfree, thanks for the feedback.

here is how the footer on those pages currently looks like:

![footerSidebarNew](https://user-images.githubusercontent.com/56799741/75878915-10fb6a80-5e23-11ea-9241-3cb74700ccc6.png)

**Comment by monikappv** [comment]
FIXED. See https://github.com/frictionlessdata/website-v2/issues/41#issuecomment-594488032.
