### ISSUE TITLE
Redirects failing with 'Node cannot be inserted at the specified point in the hierarchy'

### ISSUE THREAD

**Issue by chris48s** [frictionlessdata/website-v2#59]
https://github.com/frictionlessdata/website-v2/blob/master/site/.vuepress/enhanceApp.js
defines a number of redirects, but all or most of them fail to perform the redirect correctly e.g:

* https://frictionlessdata.io/field-guide/
* https://frictionlessdata.io/docs/validating-data/

The error `DOMException: "Node cannot be inserted at the specified point in the hierarchy"` is logged to the console.

**Comment by lauragift21** [comment]
Hi, @chris48s Thanks for bringing this issue to our attention. We are currently working on a fix here https://github.com/frictionlessdata/project/issues/448

**Comment by lauragift21** [comment]
I've fixed this now. Redirects works properly now you can test to see if it works for you as well @chris48s
