### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by roll** [frictionlessdata/website-v2#62]
Hi @lauragift21, could you please take a look - https://frictionlessdata.io/

**Comment by roll** [comment]
@lauragift21 
I've fixed it in this commit and in the settings:
- https://github.com/frictionlessdata/website-v2/commit/00571380edcf1d422b65d263a2cbe252ebacb516
- https://github.com/frictionlessdata/website-v2/settings

**Comment by lauragift21** [comment]
Thanks @roll I had the same issue yesterday.
